---
apiVersion: v2
name: kubeit-app-of-apps-values-chart
description: KubeIT ArgoCD app-of-apps values chart
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
  - name: kubeit-app-of-apps
    version: 0.1.19
    repository: "https://dnv-gssit.github.io/kubeit-charts/"
