---
repoURL: https://github.com/dnv-gssit/kubeit-charts.git
targetRevision: feature/repo-cleaning

globals:
  chart:
    path: charts/kubeit-deployment-chart
    ignoreMissingValueFiles: true
    skipCrds: true

applications:
  - name: standard-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
          - aux011
          - aux033
      - name: dev
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
          - eastus2
        clusterColour:
          - dev001
          - dev011
          - dev023
          - dev024
  - name: onegateway-workload
    containerOS: linux
    environments:
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
          - eastus2
        clusterColour:
          - dev011
          - dev001
  - name: onegateway-sessionmanager
    containerOS: linux
    environments:
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
          - eastus2
        clusterColour:
          - dev011
          - dev001
  - name: onegateway-redis
    chart:
      path: "charts/kubeit-redis-chart"
    containerOS: linux
    environments:
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
          - eastus2
        clusterColour:
          - dev011
          - dev001
  - name: onegateway-reverseproxy-workload
    containerOS: linux
    environments:
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
          - aux011
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
          - eastus2
        clusterColour:
          - dev011
  - name: onegateway-secrets
    chart:
      path: "charts/kubeit-secrets"
    containerOS: linux
    environments:
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
          - eastus2
        clusterColour:
          - dev011
          - dev001
      - name: nonprod
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - dev001
  - name: win-standard-workload
    containerOS: linux
    environments:
      - name: prod
        namespaces:
          - win-standard-workload
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: nonprod
        namespaces:
          - win-standard-workload
        region:
          - westeurope
        clusterColour:
          - blue
      - name: dev
        namespaces:
          - win-standard-workload
        region:
          - westeurope
          - eastus2
        clusterColour:
          - blue
          - green
  - name: win-api-workload
    containerOS: linux
    environments:
      - name: dev
        namespaces:
          - win-standard-workload
        region:
          - westeurope
          - eastus2
        clusterColour:
          - dev033
      - name: nonprod
        namespaces:
          - win-standard-workload
        region:
          - westeurope
        clusterColour:
          - blue
