---
# app-in-logical-env chart to use to generate application within one logical env
global:
  appLogicalEnvChart:
    repoURL: https://dnv-gssit.github.io/kubeit-charts
    chart: apps-in-logical-env
    targetRevision: 0.0.1

# here should be list of teams and their logical envs
# for each team/logcal env enabled, folder structure should be created
# under envs folder 
  teams:
    - name: team1
      envs:
        # logical env target Kubeit clusters
        - name: dev
          targetClusters:
            dev:
              regions:
                we:
                  colours:
                    blue: true
                    green: true
                eus2:
                  colours:
                    blue: true
                    green: true
                sea:
                  colours:
                    blue: true
                    green: true
            nonprod:
              regions:
                we:
                  colours:
                    blue: false
                    green: false
                eus2:
                  colours:
                    blue: false
                    green: false
        - name: qa
          targetClusters:
            dev:
              regions:
                we:
                  colours:
                    blue: true
                    green: true
                eus2:
                  colours:
                    blue: false
                    green: true
                sea:
                  colours:
                    blue: false
                    green: true
            prod:
              regions:
                we:
                  colours:
                    blue: true
                    green: false
    - name: team2
      envs:
        # logical env target Kubeit clusters
        - name: dev
          targetClusters:
            dev:
              regions:
                we:
                  colours:
                    blue: true
                    green: true
                eus2:
                  colours:
                    blue: true
                    green: true
                sea:
                  colours:
                    blue: true
                    green: true
