---
globals:
  chart:
    ignoreMissingValueFiles: true

applications:
  - name: standard-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - standard
          - standard-nonprod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - standard
          - standard-prod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - standard
          - standard-aux
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
          - aux011
  - name: shared-secrets
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - standard
          - standard-nonprod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - standard
          - standard-prod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - standard
          - standard-aux
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
          - aux011
  - name: onegateway-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - onegateway
          - onegateway-nonprod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
          - onegateway-prod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
          - onegateway-aux
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
  - name: onegateway-sessionmanager
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - onegateway
          - onegateway-nonprod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
          - onegateway-prod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
          - onegateway-aux
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
  - name: onegateway-redis
    chart:
      path: "kubeit-redis-chart"
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - onegateway
          - onegateway-nonprod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
          - onegateway-prod
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
          - onegateway-aux
        region:
          - westeurope
        clusterColour:
          - blue
  - name: win-standard-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - win-standard-workload
          - win-standard-workload-nonprod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - win-standard-workload
          - win-standard-workload-prod
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - win-standard-workload
          - win-standard-workload-aux
        region:
          - westeurope
        clusterColour:
          - blue
          - green
          - aux011
