---
globals:
  chart:
    path: kubeit-charts/charts/kubeit-deployment-chart
    ignoreMissingValueFiles: true
    skipCrds: true

applications:
  - name: standard-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
          - aux011
          - aux033
      - name: dev
        namespaces:
          - standard
          - standard-test
        region:
          - westeurope
        clusterColour:
          - dev001
          - dev011
          - dev033
  - name: onegateway-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - dev011
  - name: onegateway-sessionmanager
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - dev011
  - name: onegateway-redis
    chart:
      path: "kubeit-charts/charts/kubeit-redis-chart"
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - aux011
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - dev011
  - name: onegateway-reverseproxy-workload
    containerOS: linux
    environments:
      - name: aux
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - blue
          - green
          - aux011
          - aux033
      - name: dev
        namespaces:
          - onegateway
        region:
          - westeurope
        clusterColour:
          - dev011
          - dev033
  - name: win-standard-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - win-standard-workload
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: prod
        namespaces:
          - win-standard-workload
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
      - name: aux
        namespaces:
          - win-standard-workload
        region:
          - westeurope
        clusterColour:
          - blue
          - green
          - aux011
          - aux033
      - name: dev
        namespaces:
          - win-standard-workload
        region:
          - westeurope
        clusterColour:
          - blue
          - green
  - name: win-api-workload
    containerOS: linux
    environments:
      - name: nonprod
        namespaces:
          - win-standard-workload
        region:
          - westeurope
          - eastus2
          - southeastasia
        clusterColour:
          - blue
          - green
