---
azureKeyVaultSecrets:
  type: external-secrets
  tenantId: "adf10e2b-b6e9-41d6-be2f-c12bb566019c"
  clientId: "894da582-54c8-4283-9b2c-0bb51e44ddc1"
  azureKeyVaults:
    - azureKeyVaultName: "KubeIT-DEV-KV-SH-WE"
      secrets:
        - k8sSecretName: ancris3-session-manager
          data:
            - k8sSecretKey: client-secret
              azureKeyVaultSecretName: ancris3-dev016-client-secret
