---
defaultRouting:
  hosts:
    - "onegateway-reverseproxy-workload-tenant2.aux016.kubeit.dnv.com"

env:
  CLIENT_ID: dd3fabfd-fb4b-4ca3-b079-d45341a56fd3

keyVaultSecrets:
  globalKeyVaultName: "KubeIT-AUX-KV-SH-WE"
