---
defaultRouting:
  kubeitDefaultHosts:
    hostsPrefix: "www-test"      # Application will be available under: https://${hostsPrefix}-${tenantName}.${env}.kubeit.dnv.com/, instead of https://${app}-${tenantName}.${env}.kubeit.dnv.com/
