---
defaultRouting:
  hosts:
    - "ancris3.nonprod.kubeit.dnv.com"

env:
  CLIENT_ID: a5b67334-627a-43ca-87a3-73662f5ff44f

keyVaultSecrets:
  keyVaults:
    - keyVaultName: "KubeIT-NONPROD-KV-SH-WE"
      namespace: onegateway
      secrets:
        - keyVaultSecretName: ancris3-client-secret
          k8sSecret: enabled
          k8sSecretName: ancris3-session-manager
          k8sSecretKey: client-secret
